## Frozen reference generated by the LIVE RTSA package (Copenhagen Trial Unit's
## TSA implementation), read back with dget():
##   ref <- dget(system.file("extdata", "rtsa_0.2.2_reference.R", package = "tsahr"))
##
## Provenance
##   RTSA version : 0.2.2   (stopifnot(as.character(packageVersion("RTSA")) == "0.2.2"))
##   Run by       : the tsahr maintainer, in their own R session, September 2026
##   Numbers      : printed with print(x, digits = 16) and transcribed verbatim
##   R version    : R version 4.6.1 (2026-06-24 ucrt), platform x86_64-w64-mingw32
##                  (R.version.string / R.version$platform as reported by the
##                  maintainer for their session; the same environment as their
##                  devtools::check() runs -- correct this line if the RTSA run
##                  was made in a different session)
##
## The two calls (both alpha = 0.05, beta = 0.20, side = 2, futility =
## "non-binding", es_alpha = "esOF", es_beta = "esOF"):
##
##   design   : RTSA::boundaries(timing = c(0.25, 0.50, 0.75, 1.00),
##                               type = "design")
##   analysis : RTSA::boundaries(timing = c(0.25, 0.50, 0.75, 1.00),
##                               type = "analysis",
##                               design_R = <the design root above>)
##
## NOTE on the analysis call. Its timing does NOT end at design_R, so RTSA's
## beta_boundary() appends design_R to the information scale itself: the beta
## bounds and spend vectors therefore have FIVE elements while the alpha bounds
## have four (alpha spending is on t, not on t / design_R, because no timing
## exceeds 1). RTSA emitted the (harmless) recycling warning "zb * info$sd_proc"
## three times. This is a different call shape from the one RTSA() uses
## internally (timing extended with design_R); tsahr reproduces both shapes,
## but only this one is frozen live.
##
## `beta_ubound` NA marks RTSA's suppressed first look (zero beta spend).
list(
  rtsa_version = "0.2.2",
  alpha = 0.05, beta = 0.20, side = 2L,
  futility = "non-binding", es_alpha = "esOF", es_beta = "esOF",

  design = list(
    timing = c(0.25, 0.50, 0.75, 1.00),
    root = 1.133241903483384,
    alpha_ubound = c(4.332633646049564, 2.963130728293607,
                     2.359044407368292, 2.014090377368289),
    alpha_lbound = c(-4.332633646049564, -2.963130728293607,
                     -2.359044407368292, -2.014090377368289),
    beta_ubound = c(NA_real_, 0.6325313124459123,
                    1.4041617881408750, 2.0140903773682739),
    beta_lbound = c(NA_real_, -0.6325313124459123,
                    -1.4041617881408750, -2.0140903773682739),
    bs_incr = c(0.00000000000000000, 0.06992632672050636,
                0.06899809091886522, 0.06107558236062838),
    bs_cum  = c(0.00000000000000000, 0.06992632672050636,
                0.13892441763937158, 0.19999999999999996),
    pwr1 = c(0.00224554192689197, 0.19430410018980879,
             0.39436552699322147, 0.20908495815153269),
    pwr2 = 0.800000127261455,
    tIe1 = c(7.366808435937955e-06, 1.517956511512504e-03,
             8.075931134794795e-03, 1.182465065532224e-02),
    tIe2 = 0.02142590511006548
  ),

  analysis = list(
    timing = c(0.25, 0.50, 0.75, 1.00),
    design_R = 1.133241903483384,
    root = 1.133241903483384,
    alpha_ubound = c(4.332633646049564, 2.963130674316038,
                     2.359044357300598, 2.014090359906189),
    alpha_lbound = c(-4.332633646049564, -2.963130674316038,
                     -2.359044357300598, -2.014090359906189),
    beta_ubound = c(NA_real_, 0.3709071738839083, 1.1440542785920043,
                    1.7200465809397056, 2.1228442649443582),
    beta_lbound = c(NA_real_, -0.3709071738839083, -1.1440542785920043,
                    -1.7200465809397056, -2.1228442649443582),
    bs_incr = c(0.00000000000000000, 0.05368666786513043, 0.06149762279042426,
                0.05730121049536563, 0.02751449884907964),
    bs_cum  = c(0.00000000000000000, 0.05368666786513043, 0.11518429065555469,
                0.17248550115092032, 0.19999999999999996),
    pwr1 = c(0.001684795867493816, 0.161401391594293869,
             0.367201700967026035, 0.243398824531239538),
    pwr2 = 0.7736867129600533,
    tIe1 = c(7.366808435937955e-06, 1.517956778321858e-03,
             8.111625206118628e-03, 1.372636193270859e-02),
    tIe2 = 0.02336331072558501
  )
)
