// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

// Copyright (C) the RTSA authors (Anne Lyngholm Soerensen, Markus Harboe Olsen,
// Theis Lange, Christian Gluud) for the algorithms and code this file is derived
// from (RTSA 0.2.2, GPL (>= 2)); copyright (C) Tarak Dhaouadi for the
// adaptation. This file is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by the Free
// Software Foundation; either version 2 of the License, or (at your option) any
// later version. See DESCRIPTION and inst/COPYRIGHTS.

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rtsa_alpha_boundary_cpp
List rtsa_alpha_boundary_cpp(NumericVector inf_frac, int side, double alpha, double design_R, double tol, int r);
RcppExport SEXP _tsahr_rtsa_alpha_boundary_cpp(SEXP inf_fracSEXP, SEXP sideSEXP, SEXP alphaSEXP, SEXP design_RSEXP, SEXP tolSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inf_frac(inf_fracSEXP);
    Rcpp::traits::input_parameter< int >::type side(sideSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type design_R(design_RSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(rtsa_alpha_boundary_cpp(inf_frac, side, alpha, design_R, tol, r));
    return rcpp_result_gen;
END_RCPP
}
// rtsa_beta_boundary_cpp
List rtsa_beta_boundary_cpp(NumericVector inf_frac, NumericVector alpha_bound, double beta, int side, double delta, int rm_bs, double design_R, double warp_root, double zninf, double tol, int r);
RcppExport SEXP _tsahr_rtsa_beta_boundary_cpp(SEXP inf_fracSEXP, SEXP alpha_boundSEXP, SEXP betaSEXP, SEXP sideSEXP, SEXP deltaSEXP, SEXP rm_bsSEXP, SEXP design_RSEXP, SEXP warp_rootSEXP, SEXP zninfSEXP, SEXP tolSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type inf_frac(inf_fracSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_bound(alpha_boundSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type side(sideSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type rm_bs(rm_bsSEXP);
    Rcpp::traits::input_parameter< double >::type design_R(design_RSEXP);
    Rcpp::traits::input_parameter< double >::type warp_root(warp_rootSEXP);
    Rcpp::traits::input_parameter< double >::type zninf(zninfSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(rtsa_beta_boundary_cpp(inf_frac, alpha_bound, beta, side, delta, rm_bs, design_R, warp_root, zninf, tol, r));
    return rcpp_result_gen;
END_RCPP
}
// rtsa_init_int_cpp
NumericVector rtsa_init_int_cpp(NumericVector wj, NumericVector zj, double delta, NumericVector stdv);
RcppExport SEXP _tsahr_rtsa_init_int_cpp(SEXP wjSEXP, SEXP zjSEXP, SEXP deltaSEXP, SEXP stdvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wj(wjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zj(zjSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stdv(stdvSEXP);
    rcpp_result_gen = Rcpp::wrap(rtsa_init_int_cpp(wj, zj, delta, stdv));
    return rcpp_result_gen;
END_RCPP
}
// rtsa_recur_int_cpp
NumericVector rtsa_recur_int_cpp(int k, NumericMatrix stdv, NumericVector zj, NumericVector last, NumericVector zj_up, NumericVector wj_up, double delta, bool bs);
RcppExport SEXP _tsahr_rtsa_recur_int_cpp(SEXP kSEXP, SEXP stdvSEXP, SEXP zjSEXP, SEXP lastSEXP, SEXP zj_upSEXP, SEXP wj_upSEXP, SEXP deltaSEXP, SEXP bsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type stdv(stdvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zj(zjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type last(lastSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zj_up(zj_upSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wj_up(wj_upSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type bs(bsSEXP);
    rcpp_result_gen = Rcpp::wrap(rtsa_recur_int_cpp(k, stdv, zj, last, zj_up, wj_up, delta, bs));
    return rcpp_result_gen;
END_RCPP
}
// rtsa_prob_cpp
double rtsa_prob_cpp(double xq, NumericVector last, NumericVector zj, int k, NumericMatrix stdv, bool bs, double delta);
RcppExport SEXP _tsahr_rtsa_prob_cpp(SEXP xqSEXP, SEXP lastSEXP, SEXP zjSEXP, SEXP kSEXP, SEXP stdvSEXP, SEXP bsSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xq(xqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type last(lastSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zj(zjSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type stdv(stdvSEXP);
    Rcpp::traits::input_parameter< bool >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rtsa_prob_cpp(xq, last, zj, k, stdv, bs, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsahr_rtsa_alpha_boundary_cpp", (DL_FUNC) &_tsahr_rtsa_alpha_boundary_cpp, 6},
    {"_tsahr_rtsa_beta_boundary_cpp", (DL_FUNC) &_tsahr_rtsa_beta_boundary_cpp, 11},
    {"_tsahr_rtsa_init_int_cpp", (DL_FUNC) &_tsahr_rtsa_init_int_cpp, 4},
    {"_tsahr_rtsa_recur_int_cpp", (DL_FUNC) &_tsahr_rtsa_recur_int_cpp, 8},
    {"_tsahr_rtsa_prob_cpp", (DL_FUNC) &_tsahr_rtsa_prob_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsahr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
