# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtsa_alpha_boundary_cpp <- function(inf_frac, side, alpha, design_R, tol, r) {
    .Call(`_tsahr_rtsa_alpha_boundary_cpp`, inf_frac, side, alpha, design_R, tol, r)
}

rtsa_beta_boundary_cpp <- function(inf_frac, alpha_bound, beta, side, delta, rm_bs, design_R, warp_root, zninf, tol, r) {
    .Call(`_tsahr_rtsa_beta_boundary_cpp`, inf_frac, alpha_bound, beta, side, delta, rm_bs, design_R, warp_root, zninf, tol, r)
}

rtsa_init_int_cpp <- function(wj, zj, delta, stdv) {
    .Call(`_tsahr_rtsa_init_int_cpp`, wj, zj, delta, stdv)
}

rtsa_recur_int_cpp <- function(k, stdv, zj, last, zj_up, wj_up, delta, bs) {
    .Call(`_tsahr_rtsa_recur_int_cpp`, k, stdv, zj, last, zj_up, wj_up, delta, bs)
}

rtsa_prob_cpp <- function(xq, last, zj, k, stdv, bs, delta) {
    .Call(`_tsahr_rtsa_prob_cpp`, xq, last, zj, k, stdv, bs, delta)
}

